<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRQFrfCw\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRQFrfCw/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerRQFrfCw.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerRQFrfCw\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerRQFrfCw\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'RQFrfCw',
    'container.build_id' => '77318cc1',
    'container.build_time' => 1516964761,
));
